apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: picolytics
  namespace: blog
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: blog-project
  source:
    repoURL: https://github.com/nmcclain/picolytics.git
    targetRevision: HEAD
    path: k8s/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
