apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-infinity
  labels:
    app: grafana
    grafana_datasource: ""
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: "Infinity"
      uid: "c36466ab-9377-43a0-9896-802aaf9b1ad5"
      orgId: 1
      type: "yesoreyeram-infinity-datasource"
      url: ""
      basicAuth: false
      basicAuthUser: ""
      isDefault: false
      jsonData:
        allowedHosts:
          - "https://argocd-server"
        auth_method: "bearerToken"
        global_queries: []
        oauthPassThru: false
        tlsSkipVerify: true
      readOnly: false
      secureJsonData:
        bearerToken: "THIS_MUST_BE_SET_MANUALLY"
