apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blog-project
  namespace: blog
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Blog Project
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: blog
    server: https://kubernetes.default.svc
  roles:
  - name: grafana-read-only
    description: Read-only privileges to blog-project
    policies:
    - p, proj:blog-project:grafana-read-only, applications, get, blog-project/*, allow
