# Default values
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argo-cd:
  controller:
    metrics:
      enabled: true
      applicationLabels:
        enabled: true
        labels: ["business_unit", "team_name"]
  dex:
    metrics:
      enabled: true
  redis:
    metrics:
      enabled: true
  server:
    metrics:
      enabled: true
  repoServer:
    metrics:
      enabled: true
  applicationSet:
    metrics:
      enabled: true
  notifications:
    metrics:
      enabled: true

victoria-metrics-single:
  enabled: true
  server:
    enabled: true
    name: server
    image:
      repository: victoriametrics/victoria-metrics
      tag: v1.95.1
      pullPolicy: IfNotPresent
    persistentVolume:
      enabled: true
      storageClass: ""
      size: 256Mi
    scrape:
      enabled: true
      config:
        global:
          scrape_interval: 15s
        scrape_configs:
          - job_name: victoriametrics
            static_configs:
              - targets: [ "localhost:8428" ]
          - job_name: picolytics
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                action: keep
                regex: picolytics
              - source_labels: [__meta_kubernetes_pod_container_port_name]
                action: keep
                regex: admin
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod

grafana:
  enabled: true
  persistence:
    enabled: true
    size: 128Mi
  admin:
    existingSecret: grafana
    userKey: user
    passwordKey: password
  plugins: 
    - yesoreyeram-infinity-datasource
    - marcusolsson-dynamictext-panel
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboardsConfigMaps:
    default: dashboards
  sidecar:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
    datasources:
      enabled: true
